ALTER TABLE study
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE study_schedule
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE user_study
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE application_status
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE help_chat_rooms
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE chat_messages
MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
