ALTER TABLE study
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE study_schedule
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE user_study
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE application_status
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE help_chat_rooms
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE chat_messages
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE application_status
MODIFY COLUMN application_progress ENUM('NOT_STARTED', 'IN_PROGRESS', 'SUCCEED', 'FAILED') NOT NULL DEFAULT 'NOT_STARTED';

ALTER TABLE application_status
MODIFY COLUMN application_process ENUM('DOCUMENT_SCREENING', 'APTITUDE_CODING_TEST', 'FIRST_INTERVIEW', 'FINAL_INTERVIEW') NOT NULL DEFAULT 'DOCUMENT_SCREENING';

