ALTER TABLE user ALTER COLUMN user_role DROP DEFAULT;
ALTER TABLE user MODIFY COLUMN user_role ENUM('ROLE_NORMAL', 'ROLE_ADMIN') DEFAULT 'ROLE_NORMAL';
UPDATE user SET user_role = 'ROLE_NORMAL' WHERE user_role = 'NORMAL';
UPDATE user SET user_role = 'ROLE_ADMIN' WHERE user_role = 'ADMIN';