name: Daily Integration Test for prod

on:
  schedule:
    - cron: '0 21 * * *' # 매일 오전 6시에 실행 ( UTC 기준 )

  workflow_dispatch: # 수동 실행 가능

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: dev # temporary for test # checkout for prod

      # 2. configure settings
      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. caching Gradle
      - name: Gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle Wrapper grant permission
      - name: Grant execute permission for gradlew
        run: echo $(pwd) && chmod +x gradlew

      # 5. create and save application.yml
      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
        shell: bash
  
      - name: Save application.yml for secrets
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        shell: bash

      # 6. create and save test_application.yml
      - name: Make test_application.yml
        run: |
          mkdir -p ./src/test/resources
          touch ./src/test/resources/application.yml
        shell: bash

      - name: Save test_application.yml for secrets
        run: echo "${{ secrets.APPLICATION_TEST }}" > ./src/test/resources/application.yml
        shell: bash

      # 7. create and save logback-variables.properties
      - name: Make logback-variables.properties
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/logback-variables.properties
        shell: bash

      - name: Save logback-variables.properties for secrets
        run: echo "${{ secrets.LOGBACK_PROPERTIES }}" > ./src/main/resources/logback-variables.properties
        shell: bash

      # 9. create and save .env.test for docker-compose
      - name: Make .env.test
        run: |
          mkdir -p ./docker/conf
          touch ./docker/conf/.env.test
        shell: bash

      - name: Save .env.test for secrets
        run: echo "${{ secrets.ENV_TEST }}" > ./docker/conf/.env.test
        shell: bash

      # 10. create and save mongo-init.js for docker-compose
      - name: Make mongo-init.js
        run: |
          mkdir -p ./docker/mongo/test
          touch ./docker/mongo/test/mongo-init.js
        shell: bash

      - name: Save mongo-init.js for secrets
        run: echo "${{ secrets.MONGO_INIT }}" > ./docker/mongo/test/mongo-init.js
        shell: bash

      - name: Make mongodb.key
        run: |
          mkdir -p ./docker/mongo/etc
          touch ./docker/mongo/etc/mongodb.key
        shell: bash

      - name: Save mongodb.key for secrets
        run: |
          echo "${{ secrets.MONGO_KEY }}" > ./docker/mongo/etc/mongodb.key
          chmod 400 ./docker/mongo/etc/mongodb.key
          sudo chown 999:999 ./docker/mongo/etc/mongodb.key
        shell: bash

      # 11. create and save my.cnf for docker-compose
      - name: Make my.cnf
        run: |
          mkdir -p ./docker/mysql/conf.d
          touch ./docker/mysql/conf.d/my.cnf
        shell: bash

      - name: Save my.cnf for secrets
        run: echo "${{ secrets.MY_CNF }}" > ./docker/mysql/conf.d/my.cnf
        shell: bash

      # 12. create and save redis.conf for docker-compose
      - name: Make redis.conf
        run: |
          mkdir -p ./docker/redis
          touch ./docker/redis/redis.conf
        shell: bash

      - name: Save redis.conf for secrets
        run: echo "${{ secrets.REDIS_CNF }}" > ./docker/redis/redis.conf
        shell: bash

      # 13. set-up docker-compose for test-container
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          echo $(docker-compose --version)

      - name: Set-up docker-compose
        run: |
          if [ ! -z "$(docker ps -q)" ]; then
            docker stop $(docker ps -q)
          fi
          if [ ! -z "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
          fi
          if [ ! -z "$(docker volume ls -q)" ]; then
            docker volume rm $(docker volume ls -q)
          fi
          echo "Waiting for services to be ready..."
          docker-compose --env-file=./docker/conf/.env.test -f docker-compose-for-test.yml up -d --wait --wait-timeout 130
        shell: bash

      # 14. Wait for Services to be Ready and Check docker-compose status
      - name: Wait and Check docker-compose status
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Docker Compose failed to start all services within the timeout period."
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ *테스트 컨테이너 환경 구축 실패*: docker-compose 컨테이너를 띄우는 데 문제가 발생했습니다."}' \
          $SLACK_WEBHOOK_URL

      # 15. build test
      - name: Build test without tests
        run: ./gradlew clean build -x test

      # 16. run integration tests
      - name: Run integration tests 
        run: ./gradlew --info test

      # 17. upload test-results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: test-results/ # directory for test-results

      # 18. notify team-slack
      - name: Notify team-slack
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Sending Notification for test failure..."
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ *통합 테스트 실패*: production 브랜치 코드에서 문제가 발생했습니다."}' \
          $SLACK_WEBHOOK_URL
        
